2019-09-06T17:06:04.287073+00:00 app[worker.1]: at WebSocket.onMessage (/app/node_modules/ws/lib/event-target.js:120:16)
2019-09-06T17:06:04.287075+00:00 app[worker.1]: at WebSocket.emit (events.js:198:13)
2019-09-06T17:06:04.287076+00:00 app[worker.1]: at Receiver.receiverOnMessage (/app/node_modules/ws/lib/websocket.js:789:20)
2019-09-06T17:06:04.287077+00:00 app[worker.1]: at Receiver.emit (events.js:198:13)
2019-09-06T17:21:18.056189+00:00 heroku[worker.1]: State changed from crashed to starting
2019-09-06T17:21:20.588199+00:00 heroku[worker.1]: Starting process with command `node index.js`
2019-09-06T17:21:21.164854+00:00 heroku[worker.1]: State changed from starting to up
2019-09-06T17:21:23.269613+00:00 app[worker.1]: (node:4) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 message listeners added. Use emitter.setMaxListeners() to increase limit
2019-09-06T17:21:23.823084+00:00 app[worker.1]: Logged in as QualityBot V2#0474!
2019-09-06T18:15:34.200692+00:00 app[worker.1]: [] sent &ping
2019-09-06T18:15:51.885280+00:00 heroku[worker.1]: State changed from up to crashed
2019-09-06T18:15:51.859813+00:00 heroku[worker.1]: Process exited with status 1
2019-09-06T18:15:51.767541+00:00 app[worker.1]: /app/index.js:145
2019-09-06T18:15:51.767551+00:00 app[worker.1]: console.log(message.guild.members.get(message.author.id).displayName + " sent &help")
2019-09-06T18:15:51.767553+00:00 app[worker.1]: ^
2019-09-06T18:15:51.767554+00:00 app[worker.1]: 
2019-09-06T18:15:51.767556+00:00 app[worker.1]: ReferenceError: message is not defined
2019-09-06T18:15:51.767558+00:00 app[worker.1]: at Client.client.on.msg (/app/index.js:145:15)
2019-09-06T18:15:51.767559+00:00 app[worker.1]: at Client.emit (events.js:203:15)
2019-09-06T18:15:51.767560+00:00 app[worker.1]: at MessageCreateHandler.handle (/app/node_modules/discord.js/src/client/websocket/packets/handlers/MessageCreate.js:9:34)
2019-09-06T18:15:51.767562+00:00 app[worker.1]: at WebSocketPacketManager.handle (/app/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:105:65)
2019-09-06T18:15:51.767564+00:00 app[worker.1]: at WebSocketConnection.onPacket (/app/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:333:35)
2019-09-06T18:15:51.767565+00:00 app[worker.1]: at WebSocketConnection.onMessage (/app/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:296:17)
2019-09-06T18:15:51.767567+00:00 app[worker.1]: at WebSocket.onMessage (/app/node_modules/ws/lib/event-target.js:120:16)
2019-09-06T18:15:51.767568+00:00 app[worker.1]: at WebSocket.emit (events.js:198:13)
2019-09-06T18:15:51.767570+00:00 app[worker.1]: at Receiver.receiverOnMessage (/app/node_modules/ws/lib/websocket.js:789:20)
2019-09-06T18:15:51.767571+00:00 app[worker.1]: at Receiver.emit (events.js:198:13)
2019-09-06T18:15:52.143071+00:00 heroku[worker.1]: State changed from crashed to starting
2019-09-06T18:15:54.127353+00:00 heroku[worker.1]: Starting process with command `node index.js`
2019-09-06T18:15:54.789945+00:00 heroku[worker.1]: State changed from starting to up
2019-09-06T18:15:55.945238+00:00 app[worker.1]: (node:4) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 message listeners added. Use emitter.setMaxListeners() to increase limit
2019-09-06T18:15:56.384859+00:00 app[worker.1]: Logged in as QualityBot V2#0474!
2019-09-06T18:15:57.045337+00:00 heroku[worker.1]: State changed from up to crashed
2019-09-06T18:15:56.980569+00:00 app[worker.1]: /app/index.js:204
2019-09-06T18:15:56.980584+00:00 app[worker.1]: console.log(message.guild.members.get(message.author.id).displayName + " sent &helpme")
2019-09-06T18:15:56.980586+00:00 app[worker.1]: ^
2019-09-06T18:15:56.980587+00:00 app[worker.1]: 
2019-09-06T18:15:56.980588+00:00 app[worker.1]: ReferenceError: message is not defined
2019-09-06T18:15:56.980590+00:00 app[worker.1]: at Client.client.on.msg (/app/index.js:204:15)
2019-09-06T18:15:56.980591+00:00 app[worker.1]: at Client.emit (events.js:203:15)
2019-09-06T18:15:56.980592+00:00 app[worker.1]: at MessageCreateHandler.handle (/app/node_modules/discord.js/src/client/websocket/packets/handlers/MessageCreate.js:9:34)
2019-09-06T18:15:56.980593+00:00 app[worker.1]: at WebSocketPacketManager.handle (/app/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:105:65)
2019-09-06T18:15:56.980595+00:00 app[worker.1]: at WebSocketConnection.onPacket (/app/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:333:35)
2019-09-06T18:15:56.980596+00:00 app[worker.1]: at WebSocketConnection.onMessage (/app/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:296:17)
2019-09-06T18:15:56.980597+00:00 app[worker.1]: at WebSocket.onMessage (/app/node_modules/ws/lib/event-target.js:120:16)
2019-09-06T18:15:56.980598+00:00 app[worker.1]: at WebSocket.emit (events.js:198:13)
2019-09-06T18:15:56.980599+00:00 app[worker.1]: at Receiver.receiverOnMessage (/app/node_modules/ws/lib/websocket.js:789:20)
2019-09-06T18:15:56.980600+00:00 app[worker.1]: at Receiver.emit (events.js:198:13)
2019-09-06T18:15:57.024139+00:00 heroku[worker.1]: Process exited with status 1
2019-09-06T18:20:54.000000+00:00 app[api]: Build started by user jeremyruss43@gmail.com
2019-09-06T18:21:14.000000+00:00 app[api]: Build succeeded
2019-09-06T18:21:14.920626+00:00 heroku[worker.1]: State changed from crashed to starting
2019-09-06T18:21:13.568165+00:00 app[api]: Deploy c677868d by user jeremyruss43@gmail.com
2019-09-06T18:21:13.568165+00:00 app[api]: Release v52 created by user jeremyruss43@gmail.com
2019-09-06T18:21:17.158950+00:00 heroku[worker.1]: Starting process with command `node index.js`
2019-09-06T18:21:17.872414+00:00 heroku[worker.1]: State changed from starting to up
2019-09-06T18:21:19.375612+00:00 app[worker.1]: (node:4) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 message listeners added. Use emitter.setMaxListeners() to increase limit
2019-09-06T18:21:21.743381+00:00 app[worker.1]: Logged in as QualityBot V2#0474!
2019-09-06T18:21:37.495091+00:00 app[worker.1]: fam squad sent &ping
2019-09-06T18:21:56.795110+00:00 app[worker.1]: [] sent &ping
2019-09-06T18:21:58.419144+00:00 app[worker.1]: /app/index.js:163
2019-09-06T18:21:58.419156+00:00 app[worker.1]: console.log(msg.guild.members.get(message.author.id).displayName + " sent &bitrate")
2019-09-06T18:21:58.419158+00:00 app[worker.1]: ^
2019-09-06T18:21:58.419159+00:00 app[worker.1]: 
2019-09-06T18:21:58.419160+00:00 app[worker.1]: ReferenceError: message is not defined
2019-09-06T18:21:58.419162+00:00 app[worker.1]: at Client.client.on.msg (/app/index.js:163:37)
2019-09-06T18:21:58.419164+00:00 app[worker.1]: at Client.emit (events.js:203:15)
2019-09-06T18:21:58.419166+00:00 app[worker.1]: at MessageCreateHandler.handle (/app/node_modules/discord.js/src/client/websocket/packets/handlers/MessageCreate.js:9:34)
2019-09-06T18:21:58.419168+00:00 app[worker.1]: at WebSocketPacketManager.handle (/app/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:105:65)
2019-09-06T18:21:58.419170+00:00 app[worker.1]: at WebSocketConnection.onPacket (/app/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:333:35)
2019-09-06T18:21:58.419171+00:00 app[worker.1]: at WebSocketConnection.onMessage (/app/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:296:17)
2019-09-06T18:21:58.419173+00:00 app[worker.1]: at WebSocket.onMessage (/app/node_modules/ws/lib/event-target.js:120:16)
2019-09-06T18:21:58.419174+00:00 app[worker.1]: at WebSocket.emit (events.js:198:13)
2019-09-06T18:21:58.419176+00:00 app[worker.1]: at Receiver.receiverOnMessage (/app/node_modules/ws/lib/websocket.js:789:20)
2019-09-06T18:21:58.419177+00:00 app[worker.1]: at Receiver.emit (events.js:198:13)
2019-09-06T18:21:58.533357+00:00 heroku[worker.1]: State changed from up to crashed
2019-09-06T18:21:58.499982+00:00 heroku[worker.1]: Process exited with status 1
2019-09-06T18:25:06.000000+00:00 app[api]: Build started by user jeremyruss43@gmail.com
2019-09-06T18:25:25.021793+00:00 app[api]: Deploy 87ceefff by user jeremyruss43@gmail.com
2019-09-06T18:25:25.021793+00:00 app[api]: Release v53 created by user jeremyruss43@gmail.com
2019-09-06T18:25:25.000000+00:00 app[api]: Build succeeded
2019-09-06T18:25:26.493538+00:00 heroku[worker.1]: State changed from crashed to starting
2019-09-06T18:25:28.617816+00:00 heroku[worker.1]: Starting process with command `node index.js`
2019-09-06T18:25:29.301818+00:00 heroku[worker.1]: State changed from starting to up
2019-09-06T18:25:30.504249+00:00 app[worker.1]: (node:4) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 message listeners added. Use emitter.setMaxListeners() to increase limit
2019-09-06T18:25:30.940366+00:00 app[worker.1]: Logged in as QualityBot V2#0474!
2019-09-06T18:25:34.216114+00:00 app[worker.1]: QualityBot V2 sent &ping
2019-09-06T18:25:36.881524+00:00 app[worker.1]: QualityBot V2 sent &ping
2019-09-06T18:25:39.286631+00:00 app[worker.1]: QualityBot V2 sent &ping
2019-09-06T18:25:45.083784+00:00 app[worker.1]: [] sent &helpme
2019-09-06T18:25:45.256908+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-09-06T18:25:45.256912+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-09-06T18:25:45.256914+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-09-06T18:25:45.256915+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-09-06T18:25:45.256981+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
2019-09-06T18:25:45.257051+00:00 app[worker.1]: (node:4) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
2019-09-06T18:25:48.483446+00:00 app[worker.1]: QualityBot V2 sent &ping
2019-09-06T18:25:49.893281+00:00 app[worker.1]: [] sent &bitrate
2019-09-06T18:27:05.304384+00:00 app[worker.1]: QualityBot V2 sent &ping
2019-09-06T18:27:18.073790+00:00 app[worker.1]: QualityBot V2 sent &ping
2019-10-03T19:19:33.326558+00:00 heroku[worker.1]: Starting process with command `node index.js`
2019-10-03T19:19:33.894618+00:00 heroku[worker.1]: State changed from starting to up
2019-10-03T19:19:35.869255+00:00 app[worker.1]: Logged in as QualityBot V2#0474!
2019-10-03T19:19:40.229296+00:00 app[worker.1]: JezzaR sent &
2019-10-03T19:19:40.433420+00:00 app[worker.1]: *notices bot* sent &
2019-10-03T19:19:40.682592+00:00 app[worker.1]: *notices bot* sent &
2019-10-03T19:19:40.918555+00:00 app[worker.1]: *notices bot* sent &
2019-10-03T19:19:41.141756+00:00 app[worker.1]: *notices bot* sent &
2019-10-03T19:19:41.363887+00:00 app[worker.1]: *notices bot* sent &
2019-10-03T19:19:47.110934+00:00 app[worker.1]: *notices bot* sent &
2019-10-03T19:19:47.331586+00:00 app[worker.1]: *notices bot* sent &
2019-10-03T19:19:47.565913+00:00 app[worker.1]: *notices bot* sent &
2019-10-03T19:19:47.841881+00:00 app[worker.1]: *notices bot* sent &
2019-10-03T19:19:48.194293+00:00 app[worker.1]: *notices bot* sent &
2019-10-03T19:19:49.638016+00:00 app[api]: Scaled to web@0:Free worker@0:Free by user jeremyruss43@gmail.com
2019-10-03T19:19:49.988305+00:00 heroku[worker.1]: State changed from up to down
2019-10-03T19:19:51.624331+00:00 heroku[worker.1]: Stopping all processes with SIGTERM
2019-10-03T19:19:51.701424+00:00 heroku[worker.1]: Process exited with status 143
2019-10-03T19:21:14.354695+00:00 app[api]: Scaled to web@0:Free worker@1:Free by user jeremyruss43@gmail.com
2019-10-03T19:21:19.745209+00:00 heroku[worker.1]: Starting process with command `node index.js`
2019-10-03T19:21:24.031405+00:00 heroku[worker.1]: State changed from starting to up
2019-10-03T19:21:24.236669+00:00 app[worker.1]: Logged in as QualityBot V2#0474!
2019-10-03T19:23:36.578581+00:00 app[api]: Starting process with command `rake` by user jeremyruss43@gmail.com
2019-10-03T19:23:38.748934+00:00 heroku[run.1738]: State changed from starting to up
2019-10-03T19:23:38.493145+00:00 heroku[run.1738]: Awaiting client
2019-10-03T19:23:38.797677+00:00 heroku[run.1738]: Starting process with command `rake`
2019-10-03T19:23:43.254113+00:00 heroku[run.1738]: State changed from up to complete
2019-10-03T19:23:43.115765+00:00 heroku[run.1738]: Process exited with status 1
2019-10-03T19:25:13.661427+00:00 app[api]: Rollback to v45 by user jeremyruss43@gmail.com
2019-10-03T19:25:13.661427+00:00 app[api]: Release v57 created by user jeremyruss43@gmail.com
2019-10-03T19:25:14.821400+00:00 heroku[worker.1]: Restarting
2019-10-03T19:25:15.636211+00:00 heroku[worker.1]: State changed from up to starting
2019-10-03T19:25:17.353053+00:00 heroku[worker.1]: Stopping all processes with SIGTERM
2019-10-03T19:25:17.443091+00:00 heroku[worker.1]: Process exited with status 143
2019-10-03T19:25:18.071006+00:00 heroku[worker.1]: Starting process with command `node index.js`
2019-10-03T19:25:18.820434+00:00 heroku[worker.1]: State changed from starting to up
2019-10-03T19:25:20.182703+00:00 app[worker.1]: (node:4) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 message listeners added. Use emitter.setMaxListeners() to increase limit
2019-10-03T19:25:20.712832+00:00 app[worker.1]: Logged in as QualityBot V2#0474!
2019-10-03T19:43:45.000000+00:00 app[api]: Build started by user jeremyruss43@gmail.com
2019-10-03T19:44:03.357262+00:00 app[api]: Release v58 created by user jeremyruss43@gmail.com
2019-10-03T19:44:03.357262+00:00 app[api]: Deploy 5a5668e8 by user jeremyruss43@gmail.com
2019-10-03T19:44:03.000000+00:00 app[api]: Build succeeded
2019-10-03T19:44:04.537812+00:00 heroku[worker.1]: Restarting
2019-10-03T19:44:04.819711+00:00 heroku[worker.1]: State changed from up to starting
2019-10-03T19:44:05.981578+00:00 heroku[worker.1]: Stopping all processes with SIGTERM
2019-10-03T19:44:06.043344+00:00 heroku[worker.1]: Process exited with status 143
2019-10-03T19:44:09.084816+00:00 heroku[worker.1]: Starting process with command `node index.js`
2019-10-03T19:44:09.832959+00:00 heroku[worker.1]: State changed from starting to up
2019-10-03T19:44:11.336965+00:00 heroku[worker.1]: State changed from up to crashed
2019-10-03T19:44:11.499615+00:00 heroku[worker.1]: State changed from crashed to starting
2019-10-03T19:44:11.319312+00:00 heroku[worker.1]: Process exited with status 1
2019-10-03T19:44:11.242859+00:00 app[worker.1]: /app/index.js:36
2019-10-03T19:44:11.242886+00:00 app[worker.1]: <<<<<<< HEAD
2019-10-03T19:44:11.242888+00:00 app[worker.1]: ^^
2019-10-03T19:44:11.242889+00:00 app[worker.1]: 
2019-10-03T19:44:11.242890+00:00 app[worker.1]: SyntaxError: Unexpected token <<
2019-10-03T19:44:11.242892+00:00 app[worker.1]: at Module._compile (internal/modules/cjs/loader.js:723:23)
2019-10-03T19:44:11.242893+00:00 app[worker.1]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
2019-10-03T19:44:11.242895+00:00 app[worker.1]: at Module.load (internal/modules/cjs/loader.js:653:32)
2019-10-03T19:44:11.242896+00:00 app[worker.1]: at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
2019-10-03T19:44:11.242897+00:00 app[worker.1]: at Function.Module._load (internal/modules/cjs/loader.js:585:3)
2019-10-03T19:44:11.242898+00:00 app[worker.1]: at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
2019-10-03T19:44:11.242900+00:00 app[worker.1]: at startup (internal/bootstrap/node.js:283:19)
2019-10-03T19:44:11.242901+00:00 app[worker.1]: at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
2019-10-03T19:44:13.322987+00:00 heroku[worker.1]: Starting process with command `node index.js`
2019-10-03T19:44:13.888490+00:00 heroku[worker.1]: State changed from starting to up
2019-10-03T19:44:14.530440+00:00 heroku[worker.1]: State changed from up to crashed
2019-10-03T19:44:14.503712+00:00 heroku[worker.1]: Process exited with status 1
2019-10-03T19:44:14.454539+00:00 app[worker.1]: /app/index.js:36
2019-10-03T19:44:14.454554+00:00 app[worker.1]: <<<<<<< HEAD
2019-10-03T19:44:14.454555+00:00 app[worker.1]: ^^
2019-10-03T19:44:14.454556+00:00 app[worker.1]: 
2019-10-03T19:44:14.454558+00:00 app[worker.1]: SyntaxError: Unexpected token <<
2019-10-03T19:44:14.454559+00:00 app[worker.1]: at Module._compile (internal/modules/cjs/loader.js:723:23)
2019-10-03T19:44:14.454560+00:00 app[worker.1]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
2019-10-03T19:44:14.454561+00:00 app[worker.1]: at Module.load (internal/modules/cjs/loader.js:653:32)
2019-10-03T19:44:14.454562+00:00 app[worker.1]: at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
2019-10-03T19:44:14.454564+00:00 app[worker.1]: at Function.Module._load (internal/modules/cjs/loader.js:585:3)
2019-10-03T19:44:14.454565+00:00 app[worker.1]: at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
2019-10-03T19:44:14.454566+00:00 app[worker.1]: at startup (internal/bootstrap/node.js:283:19)
2019-10-03T19:44:14.454567+00:00 app[worker.1]: at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
2019-10-03T19:46:15.000000+00:00 app[api]: Build started by user jeremyruss43@gmail.com
2019-10-03T19:46:37.760037+00:00 app[api]: Deploy 99bcd6cb by user jeremyruss43@gmail.com
2019-10-03T19:46:37.760037+00:00 app[api]: Release v59 created by user jeremyruss43@gmail.com
2019-10-03T19:46:39.238925+00:00 heroku[worker.1]: State changed from crashed to starting
2019-10-03T19:46:38.000000+00:00 app[api]: Build succeeded
2019-10-03T19:46:45.092837+00:00 heroku[worker.1]: Starting process with command `node index.js`
2019-10-03T19:46:45.669421+00:00 heroku[worker.1]: State changed from starting to up
2019-10-03T19:46:47.679827+00:00 app[worker.1]: Logged in as QualityBot V2#0474!
2019-10-03T19:57:14.000000+00:00 app[api]: Build started by user jeremyruss43@gmail.com
2019-10-03T19:57:34.180338+00:00 app[api]: Release v60 created by user jeremyruss43@gmail.com
2019-10-03T19:57:34.180338+00:00 app[api]: Deploy fe664649 by user jeremyruss43@gmail.com
2019-10-03T19:57:34.000000+00:00 app[api]: Build succeeded
2019-10-03T19:57:35.517797+00:00 heroku[worker.1]: Restarting
2019-10-03T19:57:35.857683+00:00 heroku[worker.1]: State changed from up to starting
2019-10-03T19:57:37.066281+00:00 heroku[worker.1]: Stopping all processes with SIGTERM
2019-10-03T19:57:37.137751+00:00 heroku[worker.1]: Process exited with status 143
2019-10-03T19:57:37.908968+00:00 heroku[worker.1]: Starting process with command `node index.js`
2019-10-03T19:57:38.498408+00:00 heroku[worker.1]: State changed from starting to up
2019-10-03T19:57:41.170854+00:00 app[worker.1]: Logged in as QualityBot V2#0474!
2019-10-03T19:58:11.441417+00:00 app[worker.1]: JezzaR sent &creeper
2019-10-03T19:59:44.646103+00:00 app[worker.1]: *notices bot* sent &creeper
2019-10-03T20:01:06.259039+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-03T20:01:06.259058+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-03T20:01:06.259060+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-03T20:01:06.259062+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-03T20:01:06.259119+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
2019-10-03T20:01:06.259699+00:00 app[worker.1]: (node:4) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
2019-10-03T20:01:10.634326+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-03T20:01:10.634349+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-03T20:01:10.634350+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-03T20:01:10.634351+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-03T20:01:10.634392+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
2019-10-03T20:01:10.843629+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-03T20:01:10.843632+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-03T20:01:10.843633+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-03T20:01:10.843634+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-03T20:01:10.843712+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 7)
2019-10-03T20:01:11.032171+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-03T20:01:11.032186+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-03T20:01:11.032188+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-03T20:01:11.032190+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-03T20:01:11.032268+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 9)
2019-10-03T20:01:11.218406+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-03T20:01:11.218409+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-03T20:01:11.218410+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-03T20:01:11.218411+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-03T20:01:11.218493+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 11)
2019-10-03T20:01:11.430597+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-03T20:01:11.430608+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-03T20:01:11.430610+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-03T20:01:11.430612+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-03T20:01:11.430621+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 13)
2019-10-03T20:01:16.336603+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-03T20:01:16.336624+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-03T20:01:16.336626+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-03T20:01:16.336627+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-03T20:01:16.336637+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 16)
2019-10-03T20:01:16.526674+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-03T20:01:16.526677+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-03T20:01:16.526678+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-03T20:01:16.526679+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-03T20:01:16.526722+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 18)
2019-10-03T20:02:19.997278+00:00 app[worker.1]: JezzaR sent &creeper
2019-10-03T20:02:20.195431+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-03T20:02:20.195435+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-03T20:02:20.195436+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-03T20:02:20.195437+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-03T20:02:20.195537+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 20)
2019-10-03T20:02:20.426136+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-03T20:02:20.426157+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-03T20:02:20.426160+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-03T20:02:20.426162+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-03T20:02:20.426212+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 22)
2019-10-03T20:02:20.618628+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-03T20:02:20.618631+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-03T20:02:20.618632+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-03T20:02:20.618634+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-03T20:02:20.618677+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 24)
2019-10-03T20:02:20.798335+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-03T20:02:20.798357+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-03T20:02:20.798360+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-03T20:02:20.798361+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-03T20:02:20.798409+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 26)
2019-10-03T20:02:20.986584+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-03T20:02:20.986587+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-03T20:02:20.986589+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-03T20:02:20.986590+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-03T20:02:20.986598+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 28)
2019-10-03T20:02:25.944973+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-03T20:02:25.944985+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-03T20:02:25.944988+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-03T20:02:25.944991+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-03T20:02:25.945051+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 31)
2019-10-03T20:02:26.117984+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-03T20:02:26.117987+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-03T20:02:26.117988+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-03T20:02:26.117989+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-03T20:02:26.118045+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 33)
2019-10-03T20:02:26.324159+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-03T20:02:26.324171+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-03T20:02:26.324174+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-03T20:02:26.324176+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-03T20:02:26.324211+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 35)
2019-10-03T20:02:26.506098+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-03T20:02:26.506147+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-03T20:02:26.506149+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-03T20:02:26.506150+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-03T20:02:26.506202+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 37)
2019-10-03T20:02:26.683424+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-03T20:02:26.683443+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-03T20:02:26.683444+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-03T20:02:26.683446+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-03T20:02:26.683454+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 39)
2019-10-03T20:02:31.556739+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-03T20:02:31.556751+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-03T20:02:31.556753+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-03T20:02:31.556754+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-03T20:02:31.556785+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 42)
2019-10-03T20:02:31.776456+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-03T20:02:31.776460+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-03T20:02:31.776461+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-03T20:02:31.776462+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-03T20:02:31.776558+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 44)
2019-10-03T20:02:31.974115+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-03T20:02:31.974126+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-03T20:02:31.974127+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-03T20:02:31.974129+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-03T20:02:31.974339+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 46)
2019-10-03T20:02:32.149301+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-03T20:02:32.149305+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-03T20:02:32.149307+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-03T20:02:32.149308+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-03T20:02:32.149349+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 48)
2019-10-03T20:02:32.331681+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-03T20:02:32.331694+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-03T20:02:32.331696+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-03T20:02:32.331697+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-03T20:02:32.331738+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 50)
2019-10-03T20:02:37.228153+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-03T20:02:37.228165+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-03T20:02:37.228168+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-03T20:02:37.228169+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-03T20:02:37.228178+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 53)
2019-10-03T20:02:37.419817+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-03T20:02:37.419821+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-03T20:02:37.419822+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-03T20:02:37.419824+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-03T20:02:37.419919+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 55)
2019-10-03T20:02:37.603340+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-03T20:02:37.603351+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-03T20:02:37.603353+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-03T20:02:37.603355+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-03T20:02:37.603393+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 57)
2019-10-03T20:02:37.799071+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-03T20:02:37.799075+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-03T20:02:37.799077+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-03T20:02:37.799079+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-03T20:02:37.799137+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 59)
2019-10-03T20:02:38.021048+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-03T20:02:38.021060+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-03T20:02:38.021061+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-03T20:02:38.021063+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-03T20:02:38.021091+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 61)
2019-10-03T20:02:42.923045+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-03T20:02:42.923063+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-03T20:02:42.923065+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-03T20:02:42.923066+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-03T20:02:42.923077+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 64)
2019-10-03T20:02:43.102435+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-03T20:02:43.102439+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-03T20:02:43.102441+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-03T20:02:43.102442+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-03T20:02:43.102484+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 66)
2019-10-03T20:02:43.291006+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-03T20:02:43.291013+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-03T20:02:43.291015+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-03T20:02:43.291016+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-03T20:02:43.291212+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 68)
2019-10-03T20:02:43.465066+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-03T20:02:43.465069+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-03T20:02:43.465071+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-03T20:02:43.465076+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-03T20:02:43.465153+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 70)
2019-10-03T20:02:43.674857+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-03T20:02:43.674867+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-03T20:02:43.674869+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-03T20:02:43.674870+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-03T20:02:43.674918+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 72)
2019-10-03T20:02:48.597016+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-03T20:02:48.597027+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-03T20:02:48.597029+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-03T20:02:48.597031+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-03T20:02:48.597082+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 75)
2019-10-03T20:02:48.810162+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-03T20:02:48.810166+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-03T20:02:48.810168+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-03T20:02:48.810169+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-03T20:02:48.810215+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 77)
2019-10-03T20:02:48.989758+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-03T20:02:48.989797+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-03T20:02:48.989799+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-03T20:02:48.989801+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-03T20:02:48.989859+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 79)
2019-10-03T20:02:49.176432+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-03T20:02:49.176436+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-03T20:02:49.176438+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-03T20:02:49.176441+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-03T20:02:49.176476+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 81)
2019-10-03T20:02:49.428898+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-03T20:02:49.428911+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-03T20:02:49.428915+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-03T20:02:49.428916+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-03T20:02:49.428923+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 83)
2019-10-03T20:02:54.256751+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-03T20:02:54.256767+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-03T20:02:54.256770+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-03T20:02:54.256771+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-03T20:02:54.256798+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 86)
2019-10-03T20:02:54.552404+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-03T20:02:54.552422+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-03T20:02:54.552425+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-03T20:02:54.552426+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-03T20:02:54.552434+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 88)
2019-10-03T20:02:54.877399+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-03T20:02:54.877410+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-03T20:02:54.877411+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-03T20:02:54.877413+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-03T20:02:54.877533+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 90)
2019-10-03T20:02:55.125984+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-03T20:02:55.125988+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-03T20:02:55.125990+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-03T20:02:55.125991+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-03T20:02:55.126110+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 92)
2019-10-03T20:02:55.347048+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-03T20:02:55.347059+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-03T20:02:55.347061+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-03T20:02:55.347063+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-03T20:02:55.347233+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 94)
2019-10-03T20:02:59.952248+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-03T20:02:59.952260+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-03T20:02:59.952262+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-03T20:02:59.952264+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-03T20:02:59.952398+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 97)
2019-10-03T20:03:00.141482+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-03T20:03:00.141486+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-03T20:03:00.141488+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-03T20:03:00.141489+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-03T20:03:00.141620+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 99)
2019-10-03T20:03:00.321609+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-03T20:03:00.321620+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-03T20:03:00.321622+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-03T20:03:00.321623+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-03T20:03:00.321813+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 101)
2019-10-03T20:03:00.512124+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-03T20:03:00.512127+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-03T20:03:00.512129+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-03T20:03:00.512131+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-03T20:03:00.512187+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 103)
2019-10-03T20:03:00.705569+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-03T20:03:00.705583+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-03T20:03:00.705586+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-03T20:03:00.705588+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-03T20:03:00.705631+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 105)
2019-10-03T20:03:05.602402+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-03T20:03:05.602412+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-03T20:03:05.602414+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-03T20:03:05.602415+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-03T20:03:05.602554+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 108)
2019-10-03T20:03:05.788755+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-03T20:03:05.788759+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-03T20:03:05.788761+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-03T20:03:05.788762+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-03T20:03:05.788792+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 110)
2019-10-03T20:03:05.969707+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-03T20:03:05.969729+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-03T20:03:05.969731+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-03T20:03:05.969732+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-03T20:03:05.969934+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 112)
2019-10-03T20:03:06.211416+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-03T20:03:06.211420+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-03T20:03:06.211422+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-03T20:03:06.211423+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-03T20:03:06.211467+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 114)
2019-10-03T20:03:06.388592+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-03T20:03:06.388611+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-03T20:03:06.388613+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-03T20:03:06.388614+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-03T20:03:06.388621+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 116)
2019-10-03T20:03:11.292914+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-03T20:03:11.292931+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-03T20:03:11.292934+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-03T20:03:11.292935+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-03T20:03:11.292942+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 119)
2019-10-03T20:03:11.482866+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-03T20:03:11.482869+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-03T20:03:11.482871+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-03T20:03:11.482872+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-03T20:03:11.482902+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 121)
2019-10-03T20:03:11.673741+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-03T20:03:11.673791+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-03T20:03:11.673794+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-03T20:03:11.673796+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-03T20:03:11.673849+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 123)
2019-10-03T20:03:11.863737+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-03T20:03:11.863740+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-03T20:03:11.863742+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-03T20:03:11.863743+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-03T20:03:11.863848+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 125)
2019-10-03T20:03:12.043547+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-03T20:03:12.043562+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-03T20:03:12.043564+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-03T20:03:12.043565+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-03T20:03:12.043728+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 127)
2019-10-03T20:03:16.970691+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-03T20:03:16.970703+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-03T20:03:16.970705+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-03T20:03:16.970706+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-03T20:03:16.970740+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 130)
2019-10-03T20:03:17.161325+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-03T20:03:17.161328+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-03T20:03:17.161330+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-03T20:03:17.161331+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-03T20:03:17.161395+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 132)
2019-10-03T20:03:17.346042+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-03T20:03:17.346062+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-03T20:03:17.346065+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-03T20:03:17.346067+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-03T20:03:17.346104+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 134)
2019-10-03T20:03:17.531996+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-03T20:03:17.532000+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-03T20:03:17.532002+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-03T20:03:17.532003+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-03T20:03:17.532134+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 136)
2019-10-03T20:03:17.710301+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-03T20:03:17.710315+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-03T20:03:17.710317+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-03T20:03:17.710319+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-03T20:03:17.710332+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 138)
2019-10-03T20:03:22.660230+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-03T20:03:22.660242+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-03T20:03:22.660244+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-03T20:03:22.660250+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-03T20:03:22.660388+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 141)
2019-10-03T20:03:22.894243+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-03T20:03:22.894247+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-03T20:03:22.894249+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-03T20:03:22.894250+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-03T20:03:22.894309+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 143)
2019-10-03T20:03:23.079690+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-03T20:03:23.079703+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-03T20:03:23.079705+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-03T20:03:23.079706+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-03T20:03:23.079741+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 145)
2019-10-03T20:03:23.254431+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-03T20:03:23.254435+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-03T20:03:23.254436+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-03T20:03:23.254438+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-03T20:03:23.254485+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 147)
2019-10-03T20:03:23.438306+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-03T20:03:23.438316+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-03T20:03:23.438318+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-03T20:03:23.438337+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-03T20:03:23.438393+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 149)
2019-10-03T20:03:28.326857+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-03T20:03:28.326862+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-03T20:03:28.326864+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-03T20:03:28.326865+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-03T20:03:28.326925+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 152)
2019-10-03T20:03:28.508928+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-03T20:03:28.508931+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-03T20:03:28.508933+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-03T20:03:28.508934+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-03T20:03:28.509007+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 154)
2019-10-03T20:03:28.695300+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-03T20:03:28.695320+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-03T20:03:28.695322+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-03T20:03:28.695323+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-03T20:03:28.695360+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 156)
2019-10-03T20:03:28.879622+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-03T20:03:28.879626+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-03T20:03:28.879628+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-03T20:03:28.879632+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-03T20:03:28.879703+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 158)
2019-10-03T20:03:29.066379+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-03T20:03:29.066401+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-03T20:03:29.066403+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-03T20:03:29.066404+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-03T20:03:29.066410+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 160)
2019-10-03T20:03:34.010729+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-03T20:03:34.010753+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-03T20:03:34.010755+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-03T20:03:34.010757+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-03T20:03:34.010764+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 163)
2019-10-03T20:03:34.186575+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-03T20:03:34.186579+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-03T20:03:34.186581+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-03T20:03:34.186582+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-03T20:03:34.186620+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 165)
2019-10-03T20:03:34.420624+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-03T20:03:34.420645+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-03T20:03:34.420648+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-03T20:03:34.420649+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-03T20:03:34.420805+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 167)
2019-10-03T20:03:34.609612+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-03T20:03:34.609615+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-03T20:03:34.609617+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-03T20:03:34.609618+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-03T20:03:34.609812+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 169)
2019-10-03T20:03:34.792773+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-03T20:03:34.792797+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-03T20:03:34.792799+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-03T20:03:34.792800+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-03T20:03:34.792829+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 171)
2019-10-03T20:03:39.710065+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-03T20:03:39.710084+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-03T20:03:39.710086+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-03T20:03:39.710087+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-03T20:03:39.710165+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 174)
2019-10-04T16:41:48.130423+00:00 app[worker.1]: *notices bot* sent &
2019-10-04T16:41:48.359437+00:00 app[worker.1]: *notices bot* sent &
2019-10-04T16:41:48.597615+00:00 app[worker.1]: *notices bot* sent &
2019-10-04T16:41:48.867509+00:00 app[worker.1]: *notices bot* sent &
2019-10-04T16:41:54.580148+00:00 app[worker.1]: *notices bot* sent &
2019-10-04T16:41:54.804498+00:00 app[worker.1]: *notices bot* sent &
2019-10-04T16:41:55.021393+00:00 app[worker.1]: *notices bot* sent &
2019-10-04T16:41:55.587010+00:00 app[worker.1]: *notices bot* sent &
2019-10-04T16:41:55.856638+00:00 app[worker.1]: *notices bot* sent &
2019-10-04T16:42:01.574098+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-04T16:42:01.574121+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T16:42:01.574123+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T16:42:01.574125+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T16:42:01.574137+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 204)
2019-10-04T16:42:01.775972+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-04T16:42:01.775975+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T16:42:01.775977+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T16:42:01.775978+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T16:42:01.776016+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 206)
2019-10-04T16:42:42.946138+00:00 app[worker.1]: [] sent &
2019-10-04T16:42:43.147385+00:00 app[worker.1]: *notices bot* sent &
2019-10-04T16:42:43.390624+00:00 app[worker.1]: *notices bot* sent &
2019-10-04T16:42:44.066429+00:00 app[worker.1]: *notices bot* sent &
2019-10-04T16:42:44.305965+00:00 app[worker.1]: *notices bot* sent &
2019-10-04T16:42:44.700899+00:00 app[worker.1]: *notices bot* sent &
2019-10-04T16:42:51.699131+00:00 app[worker.1]: *notices bot* sent &
2019-10-04T16:42:51.930893+00:00 app[worker.1]: *notices bot* sent &
2019-10-04T16:42:52.198238+00:00 app[worker.1]: *notices bot* sent &
2019-10-04T16:42:52.428519+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-04T16:42:52.428523+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T16:42:52.428525+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T16:42:52.428526+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T16:42:52.428537+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 208)
2019-10-04T16:43:27.586020+00:00 app[worker.1]: [] sent &
2019-10-04T16:43:27.820410+00:00 app[worker.1]: *notices bot* sent &
2019-10-04T16:43:28.034694+00:00 app[worker.1]: *notices bot* sent &
2019-10-04T16:43:28.248136+00:00 app[worker.1]: *notices bot* sent &
2019-10-04T16:43:28.449287+00:00 app[worker.1]: *notices bot* sent &
2019-10-04T16:43:28.772486+00:00 app[worker.1]: *notices bot* sent &
2019-10-04T16:43:33.956130+00:00 app[worker.1]: *notices bot* sent &
2019-10-04T16:43:34.256423+00:00 app[worker.1]: *notices bot* sent &
2019-10-04T16:43:34.532097+00:00 app[worker.1]: *notices bot* sent &
2019-10-04T16:43:34.793276+00:00 app[worker.1]: *notices bot* sent &
2019-10-04T16:43:35.033168+00:00 app[worker.1]: *notices bot* sent &
2019-10-04T16:43:40.362870+00:00 app[worker.1]: *notices bot* sent &
2019-10-04T16:43:40.573280+00:00 app[worker.1]: *notices bot* sent &
2019-10-04T16:43:40.817123+00:00 app[worker.1]: *notices bot* sent &
2019-10-04T16:43:41.054233+00:00 app[worker.1]: *notices bot* sent &
2019-10-04T16:43:41.318122+00:00 app[worker.1]: *notices bot* sent &
2019-10-04T16:43:47.082829+00:00 app[worker.1]: *notices bot* sent &
2019-10-04T16:43:47.281164+00:00 app[worker.1]: *notices bot* sent &
2019-10-04T16:43:47.484131+00:00 app[worker.1]: *notices bot* sent &
2019-10-04T16:43:47.733557+00:00 app[worker.1]: *notices bot* sent &
2019-10-04T16:43:47.957638+00:00 app[worker.1]: *notices bot* sent &
2019-10-04T16:43:53.670773+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-04T16:43:53.670787+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T16:43:53.670789+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T16:43:53.670791+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T16:43:53.670828+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 210)
2019-10-04T16:58:03.257543+00:00 app[worker.1]: plato.05 sent &
2019-10-04T16:58:03.453181+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-04T16:58:03.453184+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T16:58:03.453185+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T16:58:03.453186+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T16:58:03.453231+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 212)
2019-10-04T16:58:12.870073+00:00 app[worker.1]: plato.05 sent &
2019-10-04T16:58:13.061647+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-04T16:58:13.061651+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T16:58:13.061653+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T16:58:13.061656+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T16:58:13.061665+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 214)
2019-10-04T17:00:27.961090+00:00 app[worker.1]: JezzaR sent &
2019-10-04T17:00:28.144809+00:00 app[worker.1]: *notices bot* sent &
2019-10-04T17:00:28.394729+00:00 app[worker.1]: *notices bot* sent &
2019-10-04T17:00:28.666288+00:00 app[worker.1]: *notices bot* sent &
2019-10-04T17:00:29.348283+00:00 app[worker.1]: *notices bot* sent &
2019-10-04T17:00:29.628007+00:00 app[worker.1]: *notices bot* sent &
2019-10-04T17:00:35.321368+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-04T17:00:35.321386+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:00:35.321388+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:00:35.321389+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:00:35.321398+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 216)
2019-10-04T17:01:26.837628+00:00 app[worker.1]: plato.05 sent &
2019-10-04T17:01:27.051055+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-04T17:01:27.051060+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:01:27.051062+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:01:27.051063+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:01:27.051119+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 218)
2019-10-04T17:01:49.000000+00:00 app[api]: Build started by user jeremyruss43@gmail.com
2019-10-04T17:02:10.541578+00:00 app[api]: Deploy a040025a by user jeremyruss43@gmail.com
2019-10-04T17:02:10.541578+00:00 app[api]: Release v61 created by user jeremyruss43@gmail.com
2019-10-04T17:02:11.726022+00:00 heroku[worker.1]: Restarting
2019-10-04T17:02:10.000000+00:00 app[api]: Build succeeded
2019-10-04T17:02:12.032075+00:00 heroku[worker.1]: State changed from up to starting
2019-10-04T17:02:13.127256+00:00 heroku[worker.1]: Stopping all processes with SIGTERM
2019-10-04T17:02:13.208237+00:00 heroku[worker.1]: Process exited with status 143
2019-10-04T17:02:13.910210+00:00 heroku[worker.1]: Starting process with command `node index.js`
2019-10-04T17:02:14.603504+00:00 heroku[worker.1]: State changed from starting to up
2019-10-04T17:02:17.987187+00:00 app[worker.1]: Logged in as QualityBot V2#0474!
2019-10-04T17:02:59.791210+00:00 app[worker.1]: JezzaR sent uwu
2019-10-04T17:07:56.796418+00:00 app[worker.1]: [] sent &creeper
2019-10-04T17:09:28.235629+00:00 app[worker.1]: *notices bot* sent &creeper
2019-10-04T17:10:59.814222+00:00 app[worker.1]: *notices bot* sent &creeper
2019-10-04T17:12:32.957393+00:00 app[worker.1]: *notices bot* sent &creeper
2019-10-04T17:14:05.007420+00:00 app[worker.1]: *notices bot* sent &creeper
2019-10-04T17:15:37.937767+00:00 app[worker.1]: *notices bot* sent &creeper
2019-10-04T17:15:57.229736+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-04T17:15:57.229756+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:15:57.229758+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:15:57.229760+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:15:57.229822+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
2019-10-04T17:15:57.229892+00:00 app[worker.1]: (node:4) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
2019-10-04T17:15:57.430815+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-04T17:15:57.430818+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:15:57.430819+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:15:57.430820+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:15:57.430888+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
2019-10-04T17:15:57.613150+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-04T17:15:57.613168+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:15:57.613169+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:15:57.613170+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:15:57.613202+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)
2019-10-04T17:15:57.791484+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-04T17:15:57.791487+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:15:57.791489+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:15:57.791491+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:15:57.791538+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 8)
2019-10-04T17:15:57.981957+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-04T17:15:57.981970+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:15:57.981972+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:15:57.981974+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:15:57.982011+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 10)
2019-10-04T17:16:02.940132+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-04T17:16:02.940152+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:16:02.940154+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:16:02.940155+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:16:02.940186+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 13)
2019-10-04T17:16:03.169749+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-04T17:16:03.169753+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:16:03.169755+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:16:03.169756+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:16:03.169765+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 15)
2019-10-04T17:16:03.366796+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-04T17:16:03.366816+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:16:03.366818+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:16:03.366819+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:16:03.366826+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 17)
2019-10-04T17:16:03.540168+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-04T17:16:03.540171+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:16:03.540173+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:16:03.540175+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:16:03.540200+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 19)
2019-10-04T17:16:03.737965+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-04T17:16:03.737985+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:16:03.737987+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:16:03.737988+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:16:03.738088+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 21)
2019-10-04T17:16:08.601792+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-04T17:16:08.601809+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:16:08.601811+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:16:08.601813+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:16:08.601819+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 24)
2019-10-04T17:16:08.779883+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-04T17:16:08.779887+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:16:08.779888+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:16:08.779890+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:16:08.779941+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 26)
2019-10-04T17:16:08.961466+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-04T17:16:08.961479+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:16:08.961481+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:16:08.961482+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:16:08.961489+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 28)
2019-10-04T17:16:09.175399+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-04T17:16:09.175403+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:16:09.175405+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:16:09.175406+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:16:09.175437+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 30)
2019-10-04T17:16:09.345037+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-04T17:16:09.345044+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:16:09.345045+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:16:09.345047+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:16:09.345086+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 32)
2019-10-04T17:17:01.162780+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-04T17:17:01.162798+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:17:01.162801+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:17:01.162802+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:17:01.162848+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 35)
2019-10-04T17:17:01.354652+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-04T17:17:01.354656+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:17:01.354657+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:17:01.354659+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:17:01.354756+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 37)
2019-10-04T17:17:01.580806+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-04T17:17:01.580818+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:17:01.580820+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:17:01.580821+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:17:01.580828+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 39)
2019-10-04T17:17:01.762209+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-04T17:17:01.762213+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:17:01.762214+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:17:01.762216+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:17:01.762349+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 41)
2019-10-04T17:17:01.995701+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-04T17:17:01.995712+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:17:01.995714+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:17:01.995716+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:17:01.995755+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 43)
2019-10-04T17:17:06.893603+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-04T17:17:06.893618+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:17:06.893620+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:17:06.893621+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:17:06.898827+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 46)
2019-10-04T17:17:07.077373+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-04T17:17:07.077377+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:17:07.077379+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:17:07.077381+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:17:07.077402+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 48)
2019-10-04T17:17:07.260074+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-04T17:17:07.260091+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:17:07.260094+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:17:07.260095+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:17:07.260102+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 50)
2019-10-04T17:17:07.481179+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-04T17:17:07.481182+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:17:07.481184+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:17:07.481186+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:17:07.481459+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 52)
2019-10-04T17:17:07.777691+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-04T17:17:07.777703+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:17:07.777706+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:17:07.777708+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:17:07.777815+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 54)
2019-10-04T17:17:12.497517+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-04T17:17:12.497530+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:17:12.497532+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:17:12.497533+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:17:12.497579+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 57)
2019-10-04T17:31:55.962944+00:00 app[worker.1]: JezzaR sent &creeper
Terminate batch job (Y/N)? 
2019-10-04T17:16:03.540200+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 19)
2019-10-04T17:16:03.737965+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-04T17:16:03.737985+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:16:03.737987+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:16:03.737988+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:16:03.738088+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 21)
2019-10-04T17:16:08.601792+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-04T17:16:08.601809+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:16:08.601811+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:16:08.601813+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:16:08.601819+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 24)
2019-10-04T17:16:08.779883+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-04T17:16:08.779887+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:16:08.779888+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:16:08.779890+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:16:08.779941+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 26)
2019-10-04T17:16:08.961466+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-04T17:16:08.961479+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:16:08.961481+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:16:08.961482+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:16:08.961489+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 28)
2019-10-04T17:16:09.175399+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-04T17:16:09.175403+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:16:09.175405+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:16:09.175406+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:16:09.175437+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 30)
2019-10-04T17:16:09.345037+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-04T17:16:09.345044+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:16:09.345045+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:16:09.345047+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:16:09.345086+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 32)
2019-10-04T17:17:01.162780+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-04T17:17:01.162798+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:17:01.162801+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:17:01.162802+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:17:01.162848+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 35)
2019-10-04T17:17:01.354652+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-04T17:17:01.354656+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:17:01.354657+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:17:01.354659+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:17:01.354756+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 37)
2019-10-04T17:17:01.580806+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-04T17:17:01.580818+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:17:01.580820+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:17:01.580821+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:17:01.580828+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 39)
2019-10-04T17:17:01.762209+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-04T17:17:01.762213+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:17:01.762214+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:17:01.762216+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:17:01.762349+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 41)
2019-10-04T17:17:01.995701+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-04T17:17:01.995712+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:17:01.995714+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:17:01.995716+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:17:01.995755+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 43)
2019-10-04T17:17:06.893603+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-04T17:17:06.893618+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:17:06.893620+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:17:06.893621+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:17:06.898827+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 46)
2019-10-04T17:17:07.077373+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-04T17:17:07.077377+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:17:07.077379+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:17:07.077381+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:17:07.077402+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 48)
2019-10-04T17:17:07.260074+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-04T17:17:07.260091+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:17:07.260094+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:17:07.260095+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:17:07.260102+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 50)
2019-10-04T17:17:07.481179+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-04T17:17:07.481182+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:17:07.481184+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:17:07.481186+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:17:07.481459+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 52)
2019-10-04T17:17:07.777691+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-04T17:17:07.777703+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:17:07.777706+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:17:07.777708+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:17:07.777815+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 54)
2019-10-04T17:17:12.497517+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2019-10-04T17:17:12.497530+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:17:12.497532+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:17:12.497533+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:17:12.497579+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 57)
2019-10-04T17:31:55.962944+00:00 app[worker.1]: JezzaR sent &creeper
2019-10-04T17:33:10.000000+00:00 app[api]: Build started by user jeremyruss43@gmail.com
2019-10-04T17:33:27.297108+00:00 app[worker.1]: *notices bot* sent &creeper
2019-10-04T17:33:29.045134+00:00 app[api]: Deploy 52d71b18 by user jeremyruss43@gmail.com
2019-10-04T17:33:29.045134+00:00 app[api]: Release v62 created by user jeremyruss43@gmail.com
2019-10-04T17:33:29.000000+00:00 app[api]: Build succeeded
2019-10-04T17:33:30.527440+00:00 heroku[worker.1]: Restarting
2019-10-04T17:33:30.968386+00:00 heroku[worker.1]: State changed from up to starting
2019-10-04T17:33:32.505821+00:00 heroku[worker.1]: Stopping all processes with SIGTERM
2019-10-04T17:33:32.675652+00:00 heroku[worker.1]: Process exited with status 143
2019-10-04T17:33:32.818103+00:00 heroku[worker.1]: Starting process with command `node index.js`
2019-10-04T17:33:33.490825+00:00 heroku[worker.1]: State changed from starting to up
2019-10-04T17:33:35.475113+00:00 app[worker.1]: Logged in as QualityBot V2#0474!
2019-10-04T17:33:41.848904+00:00 app[worker.1]: JezzaR sent &creeper
2019-10-04T17:35:14.312125+00:00 app[worker.1]: *notices bot* sent &creeper
2019-10-04T17:36:46.574333+00:00 app[worker.1]: *notices bot* sent &creeper
2019-10-04T17:38:20.659179+00:00 app[worker.1]: *notices bot* sent &creeper
2019-10-04T17:39:54.553478+00:00 app[worker.1]: *notices bot* sent &creeper
2019-10-04T17:41:29.440912+00:00 app[worker.1]: *notices bot* sent &creeper
2019-10-04T17:42:43.135875+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Access
2019-10-04T17:42:43.135901+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:42:43.135904+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:42:43.135906+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:42:43.135954+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
2019-10-04T17:42:43.136102+00:00 app[worker.1]: (node:4) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
2019-10-04T17:42:43.306192+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Access
2019-10-04T17:42:43.306195+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:42:43.306197+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:42:43.306199+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:42:43.306246+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
2019-10-04T17:42:43.573279+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Access
2019-10-04T17:42:43.573297+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:42:43.573299+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:42:43.573300+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:42:43.573390+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)
2019-10-04T17:42:43.750261+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Access
2019-10-04T17:42:43.750264+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:42:43.750266+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:42:43.750268+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:42:43.750306+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 8)
2019-10-04T17:42:43.920281+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Access
2019-10-04T17:42:43.920601+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:42:43.920603+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:42:43.920605+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:42:43.920612+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 10)
2019-10-04T17:42:48.844737+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Access
2019-10-04T17:42:48.844755+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:42:48.844757+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:42:48.844758+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:42:48.844796+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 13)
2019-10-04T17:42:49.050720+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Access
2019-10-04T17:42:49.050723+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:42:49.050725+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:42:49.050726+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:42:49.050874+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 15)
2019-10-04T17:42:49.258644+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Access
2019-10-04T17:42:49.258660+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:42:49.258663+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:42:49.258665+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:42:49.258696+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 17)
2019-10-04T17:42:49.462303+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Access
2019-10-04T17:42:49.462306+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:42:49.462308+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:42:49.462309+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:42:49.462346+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 19)
2019-10-04T17:42:49.671784+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Access
2019-10-04T17:42:49.671802+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:42:49.671804+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:42:49.671805+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:42:49.671813+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 21)
2019-10-04T17:42:54.487723+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Access
2019-10-04T17:42:54.487739+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:42:54.487741+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:42:54.487742+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:42:54.487748+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 24)
2019-10-04T17:42:54.742549+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Access
2019-10-04T17:42:54.742563+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:42:54.742565+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:42:54.742566+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:42:54.742642+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 26)
2019-10-04T17:42:54.933365+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Access
2019-10-04T17:42:54.933369+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:42:54.933373+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:42:54.933375+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:42:54.933441+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 28)
2019-10-04T17:42:55.128081+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Access
2019-10-04T17:42:55.128096+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:42:55.128097+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:42:55.128099+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:42:55.128124+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 30)
2019-10-04T17:42:55.308158+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Access
2019-10-04T17:42:55.308162+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:42:55.308164+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:42:55.308165+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:42:55.308210+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 32)
2019-10-04T17:43:00.201786+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Access
2019-10-04T17:43:00.201806+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:43:00.201808+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:43:00.201810+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:43:00.201817+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 35)
2019-10-04T17:43:00.407179+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Access
2019-10-04T17:43:00.407183+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:43:00.407185+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:43:00.407189+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:43:00.407271+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 37)
2019-10-04T17:43:00.636436+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Access
2019-10-04T17:43:00.636455+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:43:00.636458+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:43:00.636459+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:43:00.636475+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 39)
2019-10-04T17:43:00.816392+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Access
2019-10-04T17:43:00.816396+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:43:00.816398+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:43:00.816399+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:43:00.816518+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 41)
2019-10-04T17:43:01.062044+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Access
2019-10-04T17:43:01.062057+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:43:01.062059+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:43:01.062061+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:43:01.062103+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 43)
2019-10-04T17:43:05.869347+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Access
2019-10-04T17:43:05.869359+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:43:05.869361+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:43:05.869362+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:43:05.869410+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 46)
2019-10-04T17:42:43.306192+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Access
2019-10-04T17:42:43.306195+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:42:43.306197+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:42:43.306199+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:42:43.306246+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
2019-10-04T17:42:43.573279+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Access
2019-10-04T17:42:43.573297+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:42:43.573299+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:42:43.573300+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:42:43.573390+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)
2019-10-04T17:42:43.750261+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Access
2019-10-04T17:42:43.750264+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:42:43.750266+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:42:43.750268+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:42:43.750306+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 8)
2019-10-04T17:42:43.920281+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Access
2019-10-04T17:42:43.920601+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:42:43.920603+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:42:43.920605+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:42:43.920612+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 10)
2019-10-04T17:42:48.844737+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Access
2019-10-04T17:42:48.844755+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:42:48.844757+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:42:48.844758+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:42:48.844796+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 13)
2019-10-04T17:42:49.050720+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Access
2019-10-04T17:42:49.050723+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:42:49.050725+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:42:49.050726+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:42:49.050874+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 15)
2019-10-04T17:42:49.258644+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Access
2019-10-04T17:42:49.258660+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:42:49.258663+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:42:49.258665+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:42:49.258696+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 17)
2019-10-04T17:42:49.462303+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Access
2019-10-04T17:42:49.462306+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:42:49.462308+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:42:49.462309+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:42:49.462346+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 19)
2019-10-04T17:42:49.671784+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Access
2019-10-04T17:42:49.671802+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:42:49.671804+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:42:49.671805+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:42:49.671813+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 21)
2019-10-04T17:42:54.487723+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Access
2019-10-04T17:42:54.487739+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:42:54.487741+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:42:54.487742+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:42:54.487748+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 24)
2019-10-04T17:42:54.742549+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Access
2019-10-04T17:42:54.742563+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:42:54.742565+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:42:54.742566+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:42:54.742642+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 26)
2019-10-04T17:42:54.933365+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Access
2019-10-04T17:42:54.933369+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:42:54.933373+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:42:54.933375+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:42:54.933441+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 28)
2019-10-04T17:42:55.128081+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Access
2019-10-04T17:42:55.128096+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:42:55.128097+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:42:55.128099+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:42:55.128124+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 30)
2019-10-04T17:42:55.308158+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Access
2019-10-04T17:42:55.308162+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:42:55.308164+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:42:55.308165+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:42:55.308210+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 32)
2019-10-04T17:43:00.201786+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Access
2019-10-04T17:43:00.201806+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:43:00.201808+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:43:00.201810+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:43:00.201817+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 35)
2019-10-04T17:43:00.407179+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Access
2019-10-04T17:43:00.407183+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:43:00.407185+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:43:00.407189+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:43:00.407271+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 37)
2019-10-04T17:43:00.636436+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Access
2019-10-04T17:43:00.636455+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:43:00.636458+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:43:00.636459+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:43:00.636475+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 39)
2019-10-04T17:43:00.816392+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Access
2019-10-04T17:43:00.816396+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:43:00.816398+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:43:00.816399+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:43:00.816518+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 41)
2019-10-04T17:43:01.062044+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Access
2019-10-04T17:43:01.062057+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:43:01.062059+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:43:01.062061+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:43:01.062103+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 43)
2019-10-04T17:43:05.869347+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Access
2019-10-04T17:43:05.869359+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:43:05.869361+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:43:05.869362+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:43:05.869410+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 46)
2019-10-04T19:18:09.157485+00:00 heroku[worker.1]: State changed from up to down
2019-10-04T19:18:08.837085+00:00 app[api]: Scaled to web@0:Free worker@0:Free by user jeremyruss43@gmail.com
2019-10-04T19:18:10.066602+00:00 heroku[worker.1]: Stopping all processes with SIGTERM
2019-10-04T19:18:10.137585+00:00 heroku[worker.1]: Process exited with status 143
2019-10-04T17:42:54.742563+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:42:54.742565+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:42:54.742566+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:42:54.742642+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 26)
2019-10-04T17:42:54.933365+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Access
2019-10-04T17:42:54.933369+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:42:54.933373+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:42:54.933375+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:42:54.933441+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 28)
2019-10-04T17:42:55.128081+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Access
2019-10-04T17:42:55.128096+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:42:55.128097+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:42:55.128099+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:42:55.128124+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 30)
2019-10-04T17:42:55.308158+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Access
2019-10-04T17:42:55.308162+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:42:55.308164+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:42:55.308165+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:42:55.308210+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 32)
2019-10-04T17:43:00.201786+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Access
2019-10-04T17:43:00.201806+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:43:00.201808+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:43:00.201810+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:43:00.201817+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 35)
2019-10-04T17:43:00.407179+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Access
2019-10-04T17:43:00.407183+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:43:00.407185+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:43:00.407189+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:43:00.407271+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 37)
2019-10-04T17:43:00.636436+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Access
2019-10-04T17:43:00.636455+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:43:00.636458+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:43:00.636459+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:43:00.636475+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 39)
2019-10-04T17:43:00.816392+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Access
2019-10-04T17:43:00.816396+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:43:00.816398+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:43:00.816399+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:43:00.816518+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 41)
2019-10-04T17:43:01.062044+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Access
2019-10-04T17:43:01.062057+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:43:01.062059+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:43:01.062061+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:43:01.062103+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 43)
2019-10-04T17:43:05.869347+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Access
2019-10-04T17:43:05.869359+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:43:05.869361+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:43:05.869362+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:43:05.869410+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 46)
2019-10-04T19:18:09.157485+00:00 heroku[worker.1]: State changed from up to down
2019-10-04T19:18:08.837085+00:00 app[api]: Scaled to web@0:Free worker@0:Free by user jeremyruss43@gmail.com
2019-10-04T19:18:10.066602+00:00 heroku[worker.1]: Stopping all processes with SIGTERM
2019-10-04T19:18:10.137585+00:00 heroku[worker.1]: Process exited with status 143
2019-10-04T19:18:59.638167+00:00 app[api]: Scaled to web@0:Free worker@1:Free by user jeremyruss43@gmail.com
2019-10-04T19:19:02.231259+00:00 heroku[worker.1]: Starting process with command `node index.js`
2019-10-04T19:19:02.918478+00:00 heroku[worker.1]: State changed from starting to up
2019-10-04T19:19:06.023190+00:00 app[worker.1]: Logged in as QualityBot V2#0474!
2019-10-04T19:22:48.000000+00:00 app[api]: Build started by user jeremyruss43@gmail.com
2019-10-04T19:23:08.304022+00:00 app[api]: Deploy a9761ec0 by user jeremyruss43@gmail.com
2019-10-04T19:23:08.304022+00:00 app[api]: Release v63 created by user jeremyruss43@gmail.com
2019-10-04T19:23:09.686236+00:00 heroku[worker.1]: Restarting
2019-10-04T19:23:09.800144+00:00 heroku[worker.1]: State changed from up to starting
2019-10-04T19:23:08.000000+00:00 app[api]: Build succeeded
2019-10-04T19:23:11.442617+00:00 heroku[worker.1]: Stopping all processes with SIGTERM
2019-10-04T19:23:11.568633+00:00 heroku[worker.1]: Process exited with status 143
2019-10-04T19:23:11.634941+00:00 heroku[worker.1]: Starting process with command `node index.js`
2019-10-04T19:23:12.351619+00:00 heroku[worker.1]: State changed from starting to up
2019-10-04T19:23:13.877899+00:00 heroku[worker.1]: State changed from up to crashed
2019-10-04T19:23:13.958842+00:00 heroku[worker.1]: State changed from crashed to starting
2019-10-04T19:23:13.866076+00:00 heroku[worker.1]: Process exited with status 1
2019-10-04T19:23:13.675467+00:00 app[worker.1]: /app/index.js:219
2019-10-04T19:23:13.675486+00:00 app[worker.1]: <<<<<<< HEAD
2019-10-04T19:23:13.675487+00:00 app[worker.1]: ^^
2019-10-04T19:23:13.675489+00:00 app[worker.1]: 
2019-10-04T19:23:13.675490+00:00 app[worker.1]: SyntaxError: Unexpected token <<
2019-10-04T19:23:13.675492+00:00 app[worker.1]: at Module._compile (internal/modules/cjs/loader.js:723:23)
2019-10-04T19:23:13.675493+00:00 app[worker.1]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
2019-10-04T19:23:13.675495+00:00 app[worker.1]: at Module.load (internal/modules/cjs/loader.js:653:32)
2019-10-04T19:23:13.675496+00:00 app[worker.1]: at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
2019-10-04T19:23:13.675497+00:00 app[worker.1]: at Function.Module._load (internal/modules/cjs/loader.js:585:3)
2019-10-04T19:23:13.675499+00:00 app[worker.1]: at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
2019-10-04T19:23:13.675500+00:00 app[worker.1]: at startup (internal/bootstrap/node.js:283:19)
2019-10-04T19:23:13.675501+00:00 app[worker.1]: at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
2019-10-04T19:23:15.813224+00:00 heroku[worker.1]: Starting process with command `node index.js`
2019-10-04T19:23:16.520483+00:00 heroku[worker.1]: State changed from starting to up
2019-10-04T19:23:17.965791+00:00 heroku[worker.1]: State changed from up to crashed
2019-10-04T19:23:17.977947+00:00 heroku[worker.1]: Process exited with status 1
2019-10-04T19:23:17.888626+00:00 app[worker.1]: /app/index.js:219
2019-10-04T19:23:17.888655+00:00 app[worker.1]: <<<<<<< HEAD
2019-10-04T19:23:17.888657+00:00 app[worker.1]: ^^
2019-10-04T19:23:17.888658+00:00 app[worker.1]: 
2019-10-04T19:23:17.888660+00:00 app[worker.1]: SyntaxError: Unexpected token <<
2019-10-04T19:23:17.888661+00:00 app[worker.1]: at Module._compile (internal/modules/cjs/loader.js:723:23)
2019-10-04T19:23:17.888663+00:00 app[worker.1]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
2019-10-04T19:23:17.888664+00:00 app[worker.1]: at Module.load (internal/modules/cjs/loader.js:653:32)
2019-10-04T19:23:17.888666+00:00 app[worker.1]: at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
2019-10-04T19:23:17.888667+00:00 app[worker.1]: at Function.Module._load (internal/modules/cjs/loader.js:585:3)
2019-10-04T19:23:17.888668+00:00 app[worker.1]: at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
2019-10-04T19:23:17.888670+00:00 app[worker.1]: at startup (internal/bootstrap/node.js:283:19)
2019-10-04T19:23:17.888671+00:00 app[worker.1]: at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
2019-10-04T17:42:54.742563+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:42:54.742565+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:42:54.742566+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:42:54.742642+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 26)
2019-10-04T17:42:54.933365+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Access
2019-10-04T17:42:54.933369+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:42:54.933373+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:42:54.933375+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:42:54.933441+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 28)
2019-10-04T17:42:55.128081+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Access
2019-10-04T17:42:55.128096+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:42:55.128097+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:42:55.128099+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:42:55.128124+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 30)
2019-10-04T17:42:55.308158+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Access
2019-10-04T17:42:55.308162+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:42:55.308164+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:42:55.308165+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:42:55.308210+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 32)
2019-10-04T17:43:00.201786+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Access
2019-10-04T17:43:00.201806+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:43:00.201808+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:43:00.201810+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:43:00.201817+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 35)
2019-10-04T17:43:00.407179+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Access
2019-10-04T17:43:00.407183+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:43:00.407185+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:43:00.407189+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:43:00.407271+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 37)
2019-10-04T17:43:00.636436+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Access
2019-10-04T17:43:00.636455+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:43:00.636458+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:43:00.636459+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:43:00.636475+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 39)
2019-10-04T17:43:00.816392+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Access
2019-10-04T17:43:00.816396+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:43:00.816398+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:43:00.816399+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:43:00.816518+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 41)
2019-10-04T17:43:01.062044+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Access
2019-10-04T17:43:01.062057+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:43:01.062059+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:43:01.062061+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:43:01.062103+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 43)
2019-10-04T17:43:05.869347+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Access
2019-10-04T17:43:05.869359+00:00 app[worker.1]: at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
2019-10-04T17:43:05.869361+00:00 app[worker.1]: at then (/app/node_modules/snekfetch/src/index.js:215:21)
2019-10-04T17:43:05.869362+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-04T17:43:05.869410+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 46)
2019-10-04T19:18:09.157485+00:00 heroku[worker.1]: State changed from up to down
2019-10-04T19:18:08.837085+00:00 app[api]: Scaled to web@0:Free worker@0:Free by user jeremyruss43@gmail.com
2019-10-04T19:18:10.066602+00:00 heroku[worker.1]: Stopping all processes with SIGTERM
2019-10-04T19:18:10.137585+00:00 heroku[worker.1]: Process exited with status 143
2019-10-04T19:18:59.638167+00:00 app[api]: Scaled to web@0:Free worker@1:Free by user jeremyruss43@gmail.com
2019-10-04T19:19:02.231259+00:00 heroku[worker.1]: Starting process with command `node index.js`
2019-10-04T19:19:02.918478+00:00 heroku[worker.1]: State changed from starting to up
2019-10-04T19:19:06.023190+00:00 app[worker.1]: Logged in as QualityBot V2#0474!
2019-10-04T19:22:48.000000+00:00 app[api]: Build started by user jeremyruss43@gmail.com
2019-10-04T19:23:08.304022+00:00 app[api]: Deploy a9761ec0 by user jeremyruss43@gmail.com
2019-10-04T19:23:08.304022+00:00 app[api]: Release v63 created by user jeremyruss43@gmail.com
2019-10-04T19:23:09.686236+00:00 heroku[worker.1]: Restarting
2019-10-04T19:23:09.800144+00:00 heroku[worker.1]: State changed from up to starting
2019-10-04T19:23:08.000000+00:00 app[api]: Build succeeded
2019-10-04T19:23:11.442617+00:00 heroku[worker.1]: Stopping all processes with SIGTERM
2019-10-04T19:23:11.568633+00:00 heroku[worker.1]: Process exited with status 143
2019-10-04T19:23:11.634941+00:00 heroku[worker.1]: Starting process with command `node index.js`
2019-10-04T19:23:12.351619+00:00 heroku[worker.1]: State changed from starting to up
2019-10-04T19:23:13.877899+00:00 heroku[worker.1]: State changed from up to crashed
2019-10-04T19:23:13.958842+00:00 heroku[worker.1]: State changed from crashed to starting
2019-10-04T19:23:13.866076+00:00 heroku[worker.1]: Process exited with status 1
2019-10-04T19:23:13.675467+00:00 app[worker.1]: /app/index.js:219
2019-10-04T19:23:13.675486+00:00 app[worker.1]: <<<<<<< HEAD
2019-10-04T19:23:13.675487+00:00 app[worker.1]: ^^
2019-10-04T19:23:13.675489+00:00 app[worker.1]: 
2019-10-04T19:23:13.675490+00:00 app[worker.1]: SyntaxError: Unexpected token <<
2019-10-04T19:23:13.675492+00:00 app[worker.1]: at Module._compile (internal/modules/cjs/loader.js:723:23)
2019-10-04T19:23:13.675493+00:00 app[worker.1]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
2019-10-04T19:23:13.675495+00:00 app[worker.1]: at Module.load (internal/modules/cjs/loader.js:653:32)
2019-10-04T19:23:13.675496+00:00 app[worker.1]: at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
2019-10-04T19:23:13.675497+00:00 app[worker.1]: at Function.Module._load (internal/modules/cjs/loader.js:585:3)
2019-10-04T19:23:13.675499+00:00 app[worker.1]: at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
2019-10-04T19:23:13.675500+00:00 app[worker.1]: at startup (internal/bootstrap/node.js:283:19)
2019-10-04T19:23:13.675501+00:00 app[worker.1]: at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
2019-10-04T19:23:15.813224+00:00 heroku[worker.1]: Starting process with command `node index.js`
2019-10-04T19:23:16.520483+00:00 heroku[worker.1]: State changed from starting to up
2019-10-04T19:23:17.965791+00:00 heroku[worker.1]: State changed from up to crashed
2019-10-04T19:23:17.977947+00:00 heroku[worker.1]: Process exited with status 1
2019-10-04T19:23:17.888626+00:00 app[worker.1]: /app/index.js:219
2019-10-04T19:23:17.888655+00:00 app[worker.1]: <<<<<<< HEAD
2019-10-04T19:23:17.888657+00:00 app[worker.1]: ^^
2019-10-04T19:23:17.888658+00:00 app[worker.1]: 
2019-10-04T19:23:17.888660+00:00 app[worker.1]: SyntaxError: Unexpected token <<
2019-10-04T19:23:17.888661+00:00 app[worker.1]: at Module._compile (internal/modules/cjs/loader.js:723:23)
2019-10-04T19:23:17.888663+00:00 app[worker.1]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
2019-10-04T19:23:17.888664+00:00 app[worker.1]: at Module.load (internal/modules/cjs/loader.js:653:32)
2019-10-04T19:23:17.888666+00:00 app[worker.1]: at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
2019-10-04T19:23:17.888667+00:00 app[worker.1]: at Function.Module._load (internal/modules/cjs/loader.js:585:3)
2019-10-04T19:23:17.888668+00:00 app[worker.1]: at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
2019-10-04T19:23:17.888670+00:00 app[worker.1]: at startup (internal/bootstrap/node.js:283:19)
2019-10-04T19:23:17.888671+00:00 app[worker.1]: at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
2019-10-04T19:36:40.795445+00:00 heroku[worker.1]: State changed from crashed to starting
2019-10-04T19:36:43.299106+00:00 heroku[worker.1]: Starting process with command `node index.js`
2019-10-04T19:36:44.028484+00:00 heroku[worker.1]: State changed from starting to up
2019-10-04T19:36:45.850242+00:00 heroku[worker.1]: State changed from up to crashed
2019-10-04T19:36:45.835363+00:00 heroku[worker.1]: Process exited with status 1
2019-10-04T19:36:45.768121+00:00 app[worker.1]: /app/index.js:219
2019-10-04T19:36:45.768140+00:00 app[worker.1]: <<<<<<< HEAD
2019-10-04T19:36:45.768142+00:00 app[worker.1]: ^^
2019-10-04T19:36:45.768143+00:00 app[worker.1]: 
2019-10-04T19:36:45.768144+00:00 app[worker.1]: SyntaxError: Unexpected token <<
2019-10-04T19:36:45.768146+00:00 app[worker.1]: at Module._compile (internal/modules/cjs/loader.js:723:23)
2019-10-04T19:36:45.768148+00:00 app[worker.1]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
2019-10-04T19:36:45.768149+00:00 app[worker.1]: at Module.load (internal/modules/cjs/loader.js:653:32)
2019-10-04T19:36:45.768150+00:00 app[worker.1]: at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
2019-10-04T19:36:45.768152+00:00 app[worker.1]: at Function.Module._load (internal/modules/cjs/loader.js:585:3)
2019-10-04T19:36:45.768153+00:00 app[worker.1]: at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
2019-10-04T19:36:45.768155+00:00 app[worker.1]: at startup (internal/bootstrap/node.js:283:19)
2019-10-04T19:36:45.768156+00:00 app[worker.1]: at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
